=== Craig653/CSE445_Assignments_5_6_Customer_Service_Portal/CSE445_Assignments_4_5_Customer_Service_Portal/App_Data/TicketSchema.xsd
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:simpleType name = "StatusType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Open"/>
      <xsd:enumeration value="InProgress"/>
      <xsd:enumeration value="Closed"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="TicketType">
    <xsd:sequence>
      <xsd:element name="TicketNumber" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="RequestingUsername" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Text" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Image" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Status" type="StatusType" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="Category" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:element name="Tickets">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Ticket" type="TicketType" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Craig653/CSE445_Assignments_5_6_Customer_Service_Portal/CSE445_Assignments_4_5_Customer_Service_Portal/App_Data/TicketsDatabase.xml
<?xml version="1.0" encoding="utf-8"?>
<Tickets xsi:noNamespaceSchemaLocation="TicketSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Ticket Category="Power">
    <TicketNumber>1</TicketNumber>
    <RequestingUsername>Sammy345</RequestingUsername>
    <Text>I have an issue powering on my PC</Text>
    <Image>string</Image>
    <Status>InProgress</Status>
  </Ticket>
  <Ticket Category="Error">
    <TicketNumber>2</TicketNumber>
    <RequestingUsername>Craig653</RequestingUsername>
    <Text>My PC is throwing and error when opening Outlook</Text>
    <Image>string</Image>
    <Status>InProgress</Status>
  </Ticket>
  <Ticket Category="Error">
    <TicketNumber>3</TicketNumber>
    <RequestingUsername>Chris496</RequestingUsername>
    <Text>My computer errors out when opening Microsoft Word</Text>
    <Image>string</Image>
    <Status>Open</Status>
  </Ticket>
  <Ticket Category="Updates">
    <TicketNumber>4</TicketNumber>
    <RequestingUsername>Kiera111</RequestingUsername>
    <Text>My computer won't update</Text>
    <Image>string</Image>
    <Status>Closed</Status>
  </Ticket>
  <Ticket Category="Updates">
    <TicketNumber>5</TicketNumber>
    <RequestingUsername>John890</RequestingUsername>
    <Text>The computer won't install the requested updates</Text>
    <Image>string</Image>
    <Status>InProgress</Status>
  </Ticket>
</Tickets>
